-- ============================================================================
-- SPENDA GAME CENTER V19
-- MASTER GURU -> MAPEL -> KELAS -> AKUN LOGIN
-- Aman dijalankan setelah migrasi V18.
-- ============================================================================
create extension if not exists pgcrypto;

-- Pastikan tabel inti sudah ada (aman bila V18 belum selesai seluruhnya).
create table if not exists public.question_banks (
    id uuid primary key default gen_random_uuid(),
    school_id text not null default 'SMPN2SOYOJAYA',
    game text not null,
    teacher text not null,
    teacher_user_id uuid,
    level text not null,
    class_name text not null,
    subject text not null,
    difficulty text not null default 'Semua',
    questions jsonb not null default '[]'::jsonb,
    source text not null default 'import',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create table if not exists public.teacher_profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    school_id text not null default 'SMPN2SOYOJAYA',
    full_name text not null,
    role text not null default 'teacher',
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.question_banks add column if not exists teacher_user_id uuid;

create table if not exists public.teacher_master (
    id bigint generated by default as identity primary key,
    school_id text not null default 'SMPN2SOYOJAYA',
    user_id uuid,
    full_name text not null,
    nip text,
    email text,
    no_hp text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
alter table public.teacher_master add column if not exists school_id text not null default 'SMPN2SOYOJAYA';
alter table public.teacher_master add column if not exists user_id uuid;
alter table public.teacher_master add column if not exists nip text;
alter table public.teacher_master add column if not exists email text;
alter table public.teacher_master add column if not exists no_hp text;
alter table public.teacher_master add column if not exists active boolean not null default true;
alter table public.teacher_master add column if not exists created_at timestamptz not null default now();
alter table public.teacher_master add column if not exists updated_at timestamptz not null default now();
do $$begin if not exists(select 1 from pg_constraint where conname='teacher_master_user_id_fkey') then alter table public.teacher_master add constraint teacher_master_user_id_fkey foreign key(user_id) references auth.users(id) on delete set null; end if;end$$;
create index if not exists idx_teacher_master_school on public.teacher_master(school_id);
create index if not exists idx_teacher_master_user on public.teacher_master(user_id);
create index if not exists idx_teacher_master_email on public.teacher_master(lower(email));

alter table public.teacher_profiles add column if not exists teacher_master_id bigint;
alter table public.teacher_profiles add column if not exists email text;
alter table public.teacher_profiles add column if not exists nip text;
alter table public.teacher_profiles add column if not exists no_hp text;
do $$begin if not exists(select 1 from pg_constraint where conname='teacher_profiles_teacher_master_id_fkey') then alter table public.teacher_profiles add constraint teacher_profiles_teacher_master_id_fkey foreign key(teacher_master_id) references public.teacher_master(id) on delete set null; end if;end$$;
create index if not exists idx_teacher_profiles_master on public.teacher_profiles(teacher_master_id);

create table if not exists public.teacher_assignments (
    id bigint generated by default as identity primary key,
    teacher_user_id uuid not null references auth.users(id) on delete cascade,
    subject text not null,
    level text not null,
    class_name text not null,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);
create unique index if not exists ux_teacher_assignments on public.teacher_assignments(teacher_user_id,level,class_name,subject);
create index if not exists idx_teacher_assignments_lookup on public.teacher_assignments(teacher_user_id,level,subject,class_name);

create or replace function public.sync_spenda_teacher_account(p_teacher_master_id bigint)
returns jsonb language plpgsql security definer set search_path=public as $$
declare m public.teacher_master%rowtype; u uuid;
begin
  if not public.is_spenda_admin() then raise exception 'Akses hanya untuk Admin'; end if;
  select * into m from public.teacher_master where id=p_teacher_master_id;
  if not found then raise exception 'Data guru tidak ditemukan'; end if;
  if nullif(trim(m.email),'') is null then raise exception 'Email guru belum diisi'; end if;
  select id into u from auth.users where lower(trim(email))=lower(trim(m.email)) limit 1;
  if u is null then raise exception 'Akun Supabase Auth dengan email tersebut belum dibuat'; end if;
  update public.teacher_master set user_id=u,updated_at=now() where id=m.id;
  insert into public.teacher_profiles(user_id,school_id,teacher_master_id,full_name,email,nip,no_hp,role,active)
  values(u,m.school_id,m.id,m.full_name,m.email,m.nip,m.no_hp,'teacher',m.active)
  on conflict(user_id) do update set school_id=excluded.school_id,teacher_master_id=excluded.teacher_master_id,full_name=excluded.full_name,email=excluded.email,nip=excluded.nip,no_hp=excluded.no_hp,active=excluded.active,updated_at=now();
  return jsonb_build_object('ok',true,'teacher_master_id',m.id,'user_id',u);
end;$$;
grant execute on function public.sync_spenda_teacher_account(bigint) to authenticated;

create or replace function public.handle_new_spenda_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare m public.teacher_master%rowtype; v_name text;
begin
  select * into m from public.teacher_master where nullif(trim(email),'') is not null and lower(trim(email))=lower(trim(new.email)) and school_id='SMPN2SOYOJAYA' order by id limit 1;
  if found then
    insert into public.teacher_profiles(user_id,school_id,teacher_master_id,full_name,email,nip,no_hp,role,active)
    values(new.id,m.school_id,m.id,m.full_name,m.email,m.nip,m.no_hp,'teacher',m.active)
    on conflict(user_id) do update set teacher_master_id=excluded.teacher_master_id,full_name=excluded.full_name,email=excluded.email,nip=excluded.nip,no_hp=excluded.no_hp,active=excluded.active,updated_at=now();
    update public.teacher_master set user_id=new.id,updated_at=now() where id=m.id;
  else
    v_name:=nullif(trim(coalesce(new.raw_user_meta_data->>'full_name','')),''); if v_name is null then v_name:=split_part(coalesce(new.email,''),'@',1); end if;
    insert into public.teacher_profiles(user_id,school_id,full_name,email,role,active) values(new.id,'SMPN2SOYOJAYA',coalesce(v_name,'Guru'),new.email,'teacher',true) on conflict(user_id) do nothing;
  end if; return new;
end;$$;
drop trigger if exists on_auth_user_created_spenda on auth.users;
create trigger on_auth_user_created_spenda after insert on auth.users for each row execute function public.handle_new_spenda_user();

update public.teacher_profiles p set teacher_master_id=m.id,full_name=m.full_name,email=m.email,nip=m.nip,no_hp=m.no_hp,updated_at=now() from public.teacher_master m where p.teacher_master_id is null and p.user_id=m.user_id;

alter table public.teacher_master enable row level security;
revoke all on table public.teacher_master from anon,authenticated;
grant select,insert,update,delete on public.teacher_master to authenticated;
drop policy if exists teacher_master_admin_all on public.teacher_master;
create policy teacher_master_admin_all on public.teacher_master for all to authenticated using(public.is_spenda_admin()) with check(public.is_spenda_admin());

alter table public.teacher_assignments enable row level security;
revoke all on table public.teacher_assignments from anon,authenticated;
grant select on public.teacher_assignments to authenticated;
grant insert,update,delete on public.teacher_assignments to authenticated;
drop policy if exists teacher_assignments_select_self_admin on public.teacher_assignments;
create policy teacher_assignments_select_self_admin on public.teacher_assignments for select to authenticated using(teacher_user_id=(select auth.uid()) or public.is_spenda_admin());
drop policy if exists teacher_assignments_admin_write on public.teacher_assignments;
create policy teacher_assignments_admin_write on public.teacher_assignments for all to authenticated using(public.is_spenda_admin()) with check(public.is_spenda_admin());

-- BANK INSERT: guru harus mempunyai penugasan yang cocok.
drop policy if exists question_banks_insert_teacher on public.question_banks;
create policy question_banks_insert_teacher on public.question_banks for insert to authenticated with check(
  school_id='SMPN2SOYOJAYA' and (
    public.is_spenda_admin() or (
      teacher_user_id=(select auth.uid()) and
      exists(select 1 from public.teacher_profiles p where p.user_id=(select auth.uid()) and p.school_id='SMPN2SOYOJAYA' and p.active=true and lower(trim(p.full_name))=lower(trim(teacher))) and
      exists(select 1 from public.teacher_assignments a where a.teacher_user_id=(select auth.uid()) and a.active=true and lower(trim(a.subject))=lower(trim(subject)) and lower(trim(a.level))=lower(trim(level)) and lower(trim(a.class_name))=lower(trim(class_name)))
    )
  )
);

drop policy if exists question_banks_update_teacher on public.question_banks;
create policy question_banks_update_teacher on public.question_banks for update to authenticated
using(school_id='SMPN2SOYOJAYA' and (teacher_user_id=(select auth.uid()) or public.is_spenda_admin()))
with check(school_id='SMPN2SOYOJAYA' and (public.is_spenda_admin() or (teacher_user_id=(select auth.uid()) and exists(select 1 from public.teacher_assignments a where a.teacher_user_id=(select auth.uid()) and a.active=true and lower(trim(a.subject))=lower(trim(subject)) and lower(trim(a.level))=lower(trim(level)) and lower(trim(a.class_name))=lower(trim(class_name))))));

create or replace function public.set_spenda_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end;$$;
drop trigger if exists trg_teacher_master_updated_at on public.teacher_master;
create trigger trg_teacher_master_updated_at before update on public.teacher_master for each row execute function public.set_spenda_updated_at();
drop trigger if exists trg_teacher_assignments_updated_at on public.teacher_assignments;
create trigger trg_teacher_assignments_updated_at before update on public.teacher_assignments for each row execute function public.set_spenda_updated_at();

create or replace view public.teacher_master_summary with(security_invoker=true) as
select m.id,m.school_id,m.user_id,m.full_name,m.nip,m.email,m.no_hp,m.active,count(a.id) filter(where a.active=true) as jumlah_penugasan from public.teacher_master m left join public.teacher_assignments a on a.teacher_user_id=m.user_id group by m.id,m.school_id,m.user_id,m.full_name,m.nip,m.email,m.no_hp,m.active;
grant select on public.teacher_master_summary to authenticated;

-- DATA 16 GURU AWAL. Aman dijalankan ulang: tidak menggandakan nama yang sudah ada.
do $$declare v_name text;v_nip text;begin for v_name,v_nip in select * from(values
('SUYONO, S.Pd','19670406 200012 1 004'),('SAHARUDDIN, S.Pd., Gr','19850416 2019031004'),('KAHAR B, S.Pd, Gr','19870524 201903 1 010'),('LAODE MUNASIR, A.Md','19710626 2008011005'),('MELI NURMAWATI, S.Pd.Gr','19940503 2019032017'),('RISKA WATI HARFIN, S.Pd.,Gr','19940316 2019032009'),('MASNI, S.Pd,.Gr','19920112 2019032016'),('SURIANI ASIS, S.Pd,.Gr','19900727 2019032014'),('FERONIKA R. SIDABUTAR, S.Pd.,M.Pd.Gr','NIPPPK. 19990202 202421 2 008'),('RINA, S.Pd,.Gr','NIPPPK. 19870923 202321 2 015'),('HIKMA MUNAHAR, S.Pd.,Gr','NIPPPK. 20007282025212029'),('SULTHI FALANTINA TORONE, S.Pd.Gr','NIPPPK. 200006152025212025'),('RAHMAT HIDAYAT .H, A.Md.Kom','NIPPPK. 198703022025211037'),('MISGIONO','NIPPPK. 198902022025211063'),('ISMAWATI LASAMPE','NIPPPK. 199306102025212096'),('RUSTAM','NIPPPK. 199701232025211037')) x(name,nip) loop if not exists(select 1 from public.teacher_master m where lower(trim(m.full_name))=lower(trim(v_name))) then insert into public.teacher_master(full_name,nip)values(v_name,v_nip);end if;end loop;end$$;

-- Setelah mengisi email, buat akun Auth dengan email yang sama. Trigger akan menghubungkan otomatis.
-- Jika akun dibuat sebelum email diisi, gunakan master-guru.html -> Hubungkan Akun.
